# Generated by Django 4.1.1 on 2024-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='pic06.jpg', upload_to='post_pics'),
        ),
    ]
